# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-tls:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setting GOPATH
          command: |
            go version
            go env -w GOPATH=$HOME/go
      - run: make checkfmt
      - run:
          name: Generate a root CA and a server certificate using redis helpers
          command: |
            git clone git://github.com/antirez/redis.git --branch 6.0.6
            cd redis
            ./utils/gen-test-certs.sh
            cd ..
      - run:
          name: Copy RedisAI
          command: |
            docker run --rm --entrypoint cat redislabs/redisai:edge-cpu-bionic  /usr/lib/redis/modules/redisai.so > redisai.so
            chmod 755 redisai.so
      - run:
          name: Run RedisAI with tls support
          command: |
            docker run -d -v $(pwd)/redisai.so:/data/redisai.so \
                       -v $(pwd)/redis/utils/tests/tls/:/data \
                       -p 6379:6379 redis redis-server --tls-port 6379 --port 0  \
                       --tls-cert-file /data/redis.crt  \
                       --tls-key-file /data/redis.key  \
                       --tls-ca-cert-file /data/ca.crt \
                       --tls-auth-clients no  --loadmodule /data/redisai.so
      - run:
          name: Run Examples
          command: |
            make examples TLS_CERT=redis/utils/tests/tls/redis.crt \
                          TLS_KEY=redis/utils/tests/tls/redis.key \
                          TLS_CACERT=redis/utils/tests/tls/ca.crt

  build-edge: # test with redisai:edge-cpu
    docker:
      - image: circleci/golang:1.16
      - image: redislabs/redisai:edge-cpu

    working_directory: /go/src/github.com/RedisAI/redisai-go
    steps:
      - checkout
      - run: make checkfmt
      - run: make get
      - run: make coverage
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-action/master/codecov) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-tls
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-tls
