# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-tls:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Redis with TLS support
          command: |
            git clone git://github.com/antirez/redis.git --branch 6.0.1
            cd redis
            ./utils/gen-test-certs.sh
            cd ..
      - run:
          name: Copy RedisAI
          command: |
            docker run --rm --entrypoint cat redisai/redisai:edge  /usr/lib/redis/modules/redisai.so > redisai.so

  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.13
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/redisai-go
    steps:
      - checkout
      - run: make get
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-tls
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge
      - build-tls