# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-edge: # test with redisai:edge
    docker:
      - image: circleci/golang:1.9
      - image: redisai/redisai:edge

    working_directory: /go/src/github.com/RedisAI/redisai-go
    steps:
      - checkout
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-edge